app = 'amigo-oculto-staging'
primary_region = 'lhr'

[[mounts]]
source = 'amigo_oculto_data'
destination = '/app/data'
processes = ['app']

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[env]
RUST_LOG = "debug"
DATABASE_URL = "sqlite:///app/data/amigo_oculto.db"
BASE_URL = "https://staging.amigoocultosimples.app/"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[processes]
app = "/app/amigo-oculto-backend"
