app = 'amigo-oculto'
primary_region = 'gru'

[[mounts]]
source = 'amigo_oculto_data'
destination = '/app/data'
processes = ['app']

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[env]
RUST_LOG = "debug"
DATABASE_URL = "sqlite:///app/data/amigo_oculto.db"
BASE_URL = "https://amigoocultosimples.app/"
STATIC_DIR = "/app/public"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[processes]
app = "/app/run.sh"
